Added configuration in order to use java 10
abaenglish/openjdk pull request #3
Opened 2018-10-05 10:53 UTC by rogermarte

2018-10-05 11:06 UTC, rcruzper requested changes

2018-10-05 11:06 UTC, rcruzper commented on 10-jre/Dockerfile
> +FROM adoptopenjdk/openjdk10-openj9:latest
porque no usaís alpine-slim en lugar de latest? ocupa 120mb en lugar de 400mb

2018-10-05 11:21 UTC, abbot-abaenglish submitted a review, later dismissed

2018-10-10 09:35 UTC, rcruzper approved these changes

2018-10-10 09:35 UTC, merged